["dig2://192.168.0.52".par]
acqtriggersource = "ITLA | SWTrg"
startsource = "SWcmd"
recordlengths = "50000"
pretriggers = "900"
trgoutmode = "ITLA_OR_ITLB"
itlamask = "2147483648"
itlbmask = "2147483648"
itlagatewidth = "16"
itlamainlogic = "OR"
itlapairlogic = "None"

["dig2://192.168.0.52".ch]
chenable = "True"
dcoffset = "50"
selftriggeredge = "RISE"
triggerthr = "3277"
triggerthrmode = "Relative"
